spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://spring-6-rest-mvc:8081
          predicates:
            - Path=/api/v1/*

        - id: spring-6-reactive
          uri: http://spring-6-reactive:8082
          predicates:
            - Path=/api/v2/*

        - id: spring-6-reactive-mongo
          uri: http://spring-6-reactive-mongo:8083
          predicates:
            - Path=/api/v3/*


# enable the below for troubleshooting
# the wiretaps and logging levels enable over the wire debugging
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace
